AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  Environment:
    Type: String
    AllowedValues:
      - development
      - production
      - staging
      - testing

  EventName:
    Type: String
    Default: CONCERT_LAUSANNE_2019


Resources:

  UserPool:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: users/cloudformation.yml
      Parameters:
        Environment: !Ref Environment
        EventName: !Ref EventName

  Server:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: server/cloudformation.yml
      Parameters:
        AdminUserPoolGroupName: !GetAtt UserPool.Outputs.AdminUserPoolGroupName
        CognitoUserPoolId: !GetAtt UserPool.Outputs.CognitoUserPoolId
        Environment: !Ref Environment
        EventName: !Ref EventName


Outputs:

  WebSocketURI:
    Value: !GetAtt Server.Outputs.WebSocketURI

  CognitoUserPoolId:
    Value: !GetAtt UserPool.Outputs.CognitoUserPoolId

  MobileUserPoolClientId:
    Value: !GetAtt UserPool.Outputs.MobileUserPoolClientId
