version: 2
jobs:
  deploy-wiki:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '42:38:62:83:7e:81:3e:5f:b1:9c:5f:72:b3:78:9a:bc'
      - run: git clone ${CIRCLE_REPOSITORY_URL/\.git/.wiki.git} wiki
      - run: cp -r wiki/.git docs/
      - run:
          name: Commit changes
          command: |
            export COMMIT_MESSAGE="$(git log --format=%B -n 1 ${CIRCLE_SHA1})"
            cd docs
            git config user.email "circleci@threatspan.com"
            git config user.name "CircleCI"
            git add .
            git commit -m "${COMMIT_MESSAGE}" || changes=none
            git push


workflows:
  version: 2
  deploy-wiki:
    jobs:
      - deploy-wiki:
          filters:
            branches:
              only: master
