version: 2.1

orbs:
  github-wiki: sjawhar/github-wiki@0.2.1

jobs:
  lambdas-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: cd lambdas/choice && pipenv install
      - run: cd lambdas/choice && pipenv run test

  lambdas-lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: cd lambdas/choice && pipenv install
      - run: cd lambdas/choice && pipenv run lint


workflows:
  test-and-deploy:
    jobs:
      - lambdas-test
      - lambdas-lint
      - github-wiki/build-and-push:
          name: wiki-build
          push-wiki-repo: false
          sidebar-placeholder: '{{SIDEBAR_GENERATE}}'
          filters:
            branches:
              ignore: master
      - github-wiki/build-and-push:
          name: wiki-deploy
          commit-user-email: circleci@enchanted-brain
          sidebar-placeholder: '{{SIDEBAR_GENERATE}}'
          ssh-key-fingerprint: 42:38:62:83:7e:81:3e:5f:b1:9c:5f:72:b3:78:9a:bc
          filters:
            branches:
              only: master
