version: 2.1

orbs:
  github-wiki: sjawhar/github-wiki@0.1.1

workflows:
  deploy-wiki:
    jobs:
      - github-wiki/build-and-push:
          commit-user-name: CircleCI
          commit-user-email: circleci@enchanted-brain
          sidebar-placeholder: '{{SIDEBAR_GENERATE}}'
          ssh-key-fingerprint: 42:38:62:83:7e:81:3e:5f:b1:9c:5f:72:b3:78:9a:bc
          filters:
            branches:
              only: master
